REVIEWED: Force regeneration to verify USAGE.md matches the generator
As the check is a generic one for any modified files, separate the make invocation from the check.
Add a new "doc" target that encapsulates any documentation build steps.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -20,11 +20,12 @@ jobs:
     steps:
     - uses: actions/checkout@v7
     - run: make
+    - run: make test
+    - run: make -B doc
     - run: |
-        make test
         modifiedFiles=$(git status --porcelain)
         if [ -n "$modifiedFiles" ]; then
-          printf >&2 'ERROR: The following files were modified during the test:\n%s\n' "$modifiedFiles"
+          printf >&2 'ERROR: The following checked-in files were modified during the build:\n%s\n' "$modifiedFiles"
           exit 1
         fi
     - run: make dist
