REVIEWED: Build: Ensure that the generated USAGE.md is up-to-date in CI
If a PR has been submitted that affects the documentation but the changes in USAGE.md weren't committed (or even worse not even generated because the developer didn't run the tests locally), the "make test" will leave the working copy dirty, and we'll abort now.
Don't limit the check to USAGE.md, but to any checked-in file; our build process should never modify files under source control.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -20,7 +20,13 @@ jobs:
     steps:
     - uses: actions/checkout@v7
     - run: make
-    - run: make test
+    - run: |
+        make test
+        modifiedFiles=$(git status --porcelain)
+        if [ -n "$modifiedFiles" ]; then
+          printf >&2 'ERROR: The following files were modified during the test:\n%s\n' "$modifiedFiles"
+          exit 1
+        fi
     - run: make dist
     - run: make disttest
     - run: sudo make install
